spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wechatmall1?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 123456
    hikari:
      max-lifetime: 28830000
      maximum-pool-size: 9 # 连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count
  jpa:
    show-sql: true
server:
  servlet:
    context-path: /sell